lib/chess_web/router.ex
defmodule ChessWeb.Router do
  use ChessWeb, :router

  import PhoenixGon.Controller

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :put_user_token
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  defp get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Chess.Accounts.get_user(user_id || -1)

    conn = 
    case user_id do
      nil -> put_gon(conn, current_user: nil)
      _ -> put_gon(conn, current_user: user.name)
    end

    conn
    |> assign(:current_user, user)
  end

  defp put_user_token(conn, _) do
       if current_user = conn.assigns[:current_user] do
         token = Phoenix.Token.sign(conn, "user socket", current_user.id)
         conn
         |> assign(:user_token, token)
         |> put_gon(user_token: token)
       else
         conn
         |> put_gon(user_token: nil)
       end
     end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChessWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/game/:game", PageController, :game
    resources "/users", UserController, except: [:edit]


    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", ChessWeb do
    pipe_through :api
    resources "/games", GameController, except: [:new, :edit]
    post "/join_named_game", GameController, :join_named_game
    post "/create_named_game", GameController, :create_named_game
    post "/join_random_game", GameController, :join_random_game


  end
end

lib/chess_web/templates/page/game.html.eex
<div class="row">
  <div class="col">
    <h1>Chess Game: <%= @game %></h1>
    <script>
      window.gameName = "<%= @game %>";
    </script>
  <div id="root">
      <p>Memory is not yet loaded...</p>
    </div>
  </div>
</div>

lib/chess_web/templates/page/home.html.eex
<div class="container">
	<div class="row">
		<div class="col text-center">
			<h1>My Games (<%= length(@games) %>)</h1>
		</div>
	</div>
	<div class="row">
		<div class="d-flex col-5 justify-content-center">
			<form class="form-inline" id="join-named-game">
			  <input type="text" class="form-control mb-2 mr-sm-2" id="game-name" placeholder="Game Name" name="game_name">		  
			  <button type="submit" class="btn btn-primary mb-2">Join</button>
			</form>
		</div>

		<div class="d-flex col-5 justify-content-center">
			<form class="form-inline" id="create-named-game">
			  <input type="text" class="form-control mb-2 mr-sm-2" id="game-name" placeholder="Game Name" name="game_name">		  
			  <button type="submit" class="btn btn-success mb-2">Create</button>
			</form>
		</div>

		<div class="d-flex col-2 justify-content-center">
			<form class="form-inline ml-1" id="join-random-game">
			  <button type="submit" class="btn btn-primary mb-2">Join Random Game</button>
			</form>
		</div>		
	</div>
	<div class="row">
		<div class="d-flex col justify-content-center">
			<table class="table table-striped table-hover">
				<thead class="thead-light">
					<tr>
					<th>Game Name</th>
					<th>Black Player</th>
					<th>White Player</th>
					<th></th>
					</tr>
				</thead>
				<tbody>
					<%= for game <- @games do %>
						<tr>
						<td><%= game.name %></td>
						<td><%= if game.black do game.black.name else "No one" end %></td>
						<td><%= if game.white do game.white.name else "No one" end %></td>
						<%= if game.complete == true do %>
							<td>Winner: <%= game.winner.name %></td>
						<% else %>
							<td><%= link "Play", to: page_path(@conn, :game, game.name), class: "btn btn-success btn-xs"%></td>
						<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	
</div>

lib/chess_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <div class="jumbotron">
      <h1 class="display-4">Chess!</h1>
      <p class="lead">Checkmate.</p>
    </div>
  </div>
  <div class="col">
    <h1>Log In</h1>
    <%= form_tag("/session", method: :post) do %>
        <div class="form-group">
          Email
          <input type="email" name="email" placeholder="user@example.com" >
        </div>
        <!-- passwords come later -->
        <div class="form-group">
          <button class="btn btn-primary">Log in</button>
          <%=  link "Register", to: user_path(@conn, :new) %>
        </div>
      <% end %>
  </div>
</div>

lib/chess_web/templates/page/lobby.html.eex
<div class="row">
  <div class="col">
    <h1 id="index-page">Join a Game</h1>
    Enter Game Name (default - demo):<br>
    <input id="jn" type="text">
    <p><button id="jn-btn" class="btn btn-info" style="width:100px;height:40px" onClick=joinGame()>Join</a></p>
  </div>
</div>

<script>
  function joinGame() {
    let link = document.getElementById("jn").value;
    link == "" ? link = "demo" : link;
    window.location.href = "/game/" + link ;
  }
  document.getElementById("jn")
    .addEventListener("keyup", function(event) {
    event.preventDefault();
    if (event.keyCode === 13) {
        joinGame();
    }
  });
</script>

lib/chess_web/templates/page/navbar.html.eex
<nav class="navbar sticky-top navbar-dark bg-dark">
  <%= link "Chess", to: page_path(@conn, :index), class: "navbar-brand" %>
  <%= if @current_user do %>
        <span class="nav-item navbar-text">
          Logged in as: <%= @current_user.name %> 
        </span>
        <div class="ml-auto nav-item">
          <%= link "Log Out", to: "/session", method: :delete, class: "btn btn-outline-light btn-xs" %>
        </div>
   <% end %>
</nav>

lib/chess_web/templates/page/nogame.html.eex
<div class="row">
  <div class="col">
    <h1>Sorry, a game by the name "<%= @game %>"" wasn't found!</h1>
  </div>
</div>

lib/chess_web/templates/page/pregame.html.eex
<div class="row">
  <div class="col">
    <h1>We're still waiting for enough players to join this game!</h1>
  </div>
</div>